# Runtime settings
# Make a copy of this file as 'config.yaml', set the options to match
# your system, and load into R with
#     library(yaml)
#     config <- load.yaml_file('config.yaml')
#     # access config as a list...
#     config$data$pgc_mdd_v1
## data location configuration
# pgc:mdd:v1: input location of v1 PGC MDD cohorts on LISA
# pgc:mdd:pheno: output location to write PGC symptom .pheno files
# pgc:mdd:ukb_remove: IDs of PGC participants who overlap with UK Biobank
data:
  pgc:
    mdd:
      v1: /home/PATH/v1
      pheno: /home/USER/mdd_symptoms
      ukb_remove: /home/PATH/959_PGC_UKB_overlap.txt
