MD -> Dep
MD -> Anh
MD -> UKB MH Dep
MD -> UKB MH Anh

MD.shape: circle

UKB MH Dep.shape: oval
UKB MH Anh.shape: oval

Psych: Psychological
Neuroveg: Neurovegetative

Psych.shape: circle
Neuroveg.shape: circle

Psych -> Dep
Psych -> Guilt
Psych -> Sui

Neuroveg -> Anh
Neuroveg -> App
Neuroveg -> Sle
Neuroveg -> Motor
Neuroveg -> Fatig
Neuroveg -> Conc

Psych <-> Neuroveg

Dep: Depressed mood
Anh: Anhedonia

Dep.shape: oval
Anh.shape: oval
App.shape: oval
Sle.shape: oval
Motor.shape: oval
Conc.shape: oval
Guilt.shape: oval
Fatig.shape: oval
Sui.shape: oval

Dep.PGC
Dep.AGDS
Dep.UKB MHQ Dep
Anh.PGC
Anh.AGDS
Anh.UKB MHQ Anh
App.PGC
App.AGDS
App.UKB
Sle.PGC
Sle.AGDS
Sle.UKB
Motor.PGC
Motor.AGDS
Fatig.PGC
Fatig.AGDS
Fatig.UKB
Conc.PGC
Conc.AGDS
Conc.UKB
Guilt.PGC
Guilt.AGDS
Guilt.UKB
Sui.PGC
Sui.AGDS
Sui.UKB