---
title: Stratified GenomicSEM of MDD symptoms setup
author: Mark Adams, Bradley Jermy, Jackson Thorp, Andrew Grotzinger, Michel Nivard 
output:
  html_document:
	toc: TRUE
	code_folding: hide
	number_sections: TRUE
	df_print: kable
	keep_md: true
  md_document:
	variant: markdown_github
---

Analyse [stratified LDSC covariance matrix](https://github.com/GenomicSEM/GenomicSEM/wiki/6.-Stratified-Genomic-SEM).

```{r library}
library(GenomicSEM)
library(stringr)
library(readr)
library(dplyr)
library(tidyr)
```


# Trait information


```{r symptom_labels}

dsm_mdd_symptoms_labels <-
read_delim("
MDD1;Mood;Mood;Dep
MDD2;Interest;Interest;Anh
MDD3;Weight⇅;Weight⇆;App
MDD3a;Weight⇊;Weight⇇;AppDec
MDD3b;Weight⇈;Weight⇉;AppInc
MDD4;Sleep⇅;Sleep⇆;Sle
MDD4a;Sleep⇊;Sleep⇇;SleDec
MDD4b;Sleep⇈;Sleep⇉;SleInc
MDD5;Motor⇅;Motor⇆;Psyc
MDD5a;Motor⇈;Motor⇉;PsycInc
MDD5b;Motor⇊;Motor⇇;PsycDec
MDD6;Fatigue;Fatigue;Fatig
MDD7;Guilt;Guilt;Guilt
MDD8;Concentrate;Concentrate;Conc
MDD9;Suicidality;Suicidality;Sui
", col_names=c('ref', 'h', 'v', 'abbv'), delim=';')

```

# Statified LDSC

```{r s_ldcs}

covstruct_prefix <- 'agds_pgc.alspac_ukb.s_ldsc.baseline.covstruct'
covstruct_r <- here::here('ldsc', paste(covstruct_prefix, 'deparse.R', sep='.'))
covstruct_dir <- here::here('ldsc', covstruct_prefix)

# load universal entries
symptoms_covstruct <- dget(covstruct_r)

for(entry in c('S', 'V', 'S_Tau', 'V_Tau')) {

	entry_dir <- here::here(covstruct_dir, entry)
	
	entry_list <- list()
		
	for(annot_file in list.files(entry_dir, full.names=T)) {
		annotation_matrix <- dget(annot_file)
		annot_name <- str_replace(basename(annot_file), '.deparse.R', '')
		entry_list[[annot_name]] <- annotation_matrix
	}
	
	symptoms_covstruct[[entry]] <- entry_list
}

```

```{r affect}

pop_affect.model <- "
A1 =~ PopDep + PopGuilt + PopSui
"

pop_affect.enrich <- enrich(s_covstruc=symptoms_covstruct, model=pop_affect.model,params=c("A1~~A1"), std.lv=TRUE)

```

```

