---
title: GenomicSEM of MDD symptoms sample counts
author: Mark Adams, Bradley Jermy, Jackson Thorp, Andrew Grotzinger, Michel Nivard 
output:
  github_document
---

Make table of counts of sypmtom presence/absence used in final analyses

```{r}

library(readxl)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)

```

File for aligning sumstats filenames to cohort/symptom
```{r}

cohort_alignment <- read_tsv('meta/cohort_alignment.txt')

```

List of `basic.xls` files from Ricopili with sample counts

```{r}

basic_xls_list <- list.files('meta/distribution', pattern='basic.*.xls', full.names=TRUE, recursive=TRUE)

names(basic_xls_list) <- str_match(basename(basic_xls_list), "basic\\.([A-Za-z_]+\\.MDD[0-9A-Za-z_]+)")[,2]

basics <- bind_rows(lapply(basic_xls_list, read_excel), .id='meta')

basics_datasets <- basics %>%
	filter(Dataset != 'SUM') %>%
	select(-meta) |>
	distinct()
	
basics_meta <-
basics %>%
	filter(Dataset == 'SUM') %>%
	mutate(Dataset=meta) %>%
	select(-meta)

```

Merge and reformat

```{r}

basics_aligned <- 
cohort_alignment %>%
filter(!reference %in% c('MDD3', 'MDD4')) %>%
mutate(Dataset=str_replace(str_remove(filename, pattern='daner_'), 'gz', 'align.gz')) %>%
left_join(basics_datasets, by='Dataset')

basics_summary <- basics_aligned |>
mutate(meta=case_when(cohort %in% c('PGC', 'AGDS', 'GenScot', 'janpy') ~ "Clinical",
                      cohort %in% c('ALSPAC', 'EstBB', 'UKBB') ~ "Community",
					  TRUE ~ NA_character_)) |>
group_by(meta, reference) |>
summarize(N_cases=sum(N_cases, na.rm=T), N_controls=sum(N_controls, na.rm=T), N_eff_half=sum(N_eff_half, na.rm=T)) |>
ungroup()

presence_absence <- basics_summary |>
	str_glue_data("{N_cases} : {N_controls} {round(100*N_cases/(N_cases + N_controls))}")

basics_formatted <- 
basics_summary %>%
mutate(PresenceAbsence=as.character(presence_absence)) %>%
select(meta, reference, PresenceAbsence) %>%
pivot_wider(names_from=meta, values_from=PresenceAbsence)

knitr::kable(basics_formatted)

```

```{r}

basics_sum <-
basics_aligned %>%
mutate(sample=if_else(cohort %in% c('AGDS', 'PGC', 'GenScot', 'janpy'), true='enriched', false='unselected')) %>%
group_by(sample, reference) %>%
summarise(N_cases=sum(N_cases), N_controls=sum(N_controls)) 

basics_sum %>%
group_by(sample) %>%
summarise(minCa=min(N_cases, na.rm=T), maxCa=max(N_cases, na.rm=T), minCo=min(N_controls, na.rm=T), maxCo=max(N_controls, na.rm=T))

```

Sample prevalences

```{r}

basics_sum %>% 
transmute(sample, reference, P=N_cases / (N_controls + N_cases)) %>% 
mutate(d50=abs(0.5-P)) %>%
arrange(sample, d50) %>%
print(n=Inf)

```

Datasets

```{r}

cohort_sumstats <- basics_aligned |>
	transmute(cohort, reference, dataset=str_match(Dataset, "([A-Za-z0-9_]+)")[,2],
			  N_cases, N_controls, `N_eff_half`, `LAMBDA-GC`, `N-SNPs`) |>
	filter(!is.na(N_cases))

meta_sumstats <-
basics_meta %>%
	mutate(cohort=str_match(Dataset, "([A-Za-z_]+)")[,2],
	       reference=str_match(Dataset, "(MDD[0-9a-b]+)")[,2]) |>
	select(cohort, reference, dataset=Dataset,
		   N_cases, N_controls, `N_eff_half`,
		   `LAMBDA-GC`, `N-SNPs`)
		   
sumstats <- bind_rows(cohort_sumstats, meta_sumstats)
		   
write_csv(sumstats, "meta/meta.csv")

```

Totals
```{r}
cohort_sumstats |> filter(cohort %in% c('PGC', 'AGDS', 'GenScot', 'janpy')) |>
	mutate(N=N_cases+N_controls, cohort=if_else(cohort=='PGC', true=sapply(str_split(dataset, "_"), last), false=cohort)) |>
	group_by(cohort) |>
	summarize(N=max(N)) |>
	ungroup() |>
	summarize(N=sum(N))

cohort_sumstats |> filter(cohort %in% c('ALSPAC', 'EstBB', 'UKBB')) |>
	mutate(N=N_cases+N_controls) |>
	group_by(cohort) |>
	summarize(N=max(N)) |>
	ungroup() |>
	summarize(N=sum(N))
```